apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: sven-updater
spec:
  namespace: argocd
  applicationRefs:
    - namePattern:  {{ .Release.Name }}-deployment
      images:
        - alias: "sventy"
          imageName: "sven.registry.qentis.de/applications/environment-app:1.0.x"
          commonUpdateSettings:
            updateStrategy: "semver"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
