apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: rimraf-cloudflare
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Release.Name }}.{{ .Release.Namespace }}.qentis.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.port }}
  tls:
    - hosts:
        - {{ .Release.Name }}.{{ .Release.Namespace }}.qentis.de
      secretName: {{ .Release.Name }}-tls
