replicaCount: 1
image:
  repository: sven.registry.qentis.de/applications/environment-app
  tag: prod-1.0.0
externalURL: https://sven.registry.qentis.de
ingress:
  host: sven.qentis.de
  className: traefik
service:
  port: 3000
